In [28]:
import numpy as np

In [29]:
import sys
sys.version

'3.12.10 (tags/v3.12.10:0cc8128, Apr  8 2025, 12:21:36) [MSC v.1943 64 bit (AMD64)]'

In [30]:
np.version

<module 'numpy.version' from 'C:\\Users\\raavi\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\version.py'>

In [31]:
np.__version__

'2.4.0'

In [32]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [33]:
type(my_list)

list

In [34]:
arr = np.array(my_list) 
arr

array([0, 1, 2, 3, 4, 5])

In [35]:
type(arr)

numpy.ndarray

In [36]:
print(type(arr))
print(type(my_list))

<class 'numpy.ndarray'>
<class 'list'>


In [37]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [39]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [40]:
np.arange(20,10)

array([], dtype=int64)

In [41]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [42]:
np.zeros(3)

array([0., 0., 0.])

In [43]:
np.zeros(5, dtype=int) # hyperparameter tunning 

array([0, 0, 0, 0, 0])

In [44]:
z= np.zeros(3)
z

array([0., 0., 0.])

In [45]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [46]:
i=np.zeros((5,5), dtype=int)
i

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [47]:
np.ones(3)

array([1., 1., 1.])

In [48]:
np.ones(3, dtype=int)

array([1, 1, 1])

In [49]:
i= np.ones((10,10), dtype=int)
i

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [50]:
print(i)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [51]:
rand(3,2)

NameError: name 'rand' is not defined

In [52]:
random.rand(2)

NameError: name 'random' is not defined

In [53]:
np.random.rand(2)

array([0.78213991, 0.77315493])

In [54]:
np.random.rand(3)

array([0.53380826, 0.17123146, 0.30734763])

In [55]:
i=int(np.random.rand(2))
i

TypeError: only 0-dimensional arrays can be converted to Python scalars

In [56]:
np.random.rand(3,2)

array([[0.63038888, 0.64744087],
       [0.04961716, 0.79955286],
       [0.75339705, 0.38551913]])

In [60]:
i=np.random.randint(4,5)
i

4

In [62]:
i=np.random.randint(2,34)
i

28

In [63]:
i=np.random.randint(2,34)
i

26

In [65]:
i=np.random.randint(2,34,3)
i

array([33, 13, 21], dtype=int32)

In [66]:
np.random.randint(2,34,3)

array([27, 21, 29], dtype=int32)

In [68]:
np.random.randint(2,34,(10,10))

array([[ 2, 22, 26, 10,  3, 18, 23,  9, 13, 12],
       [18, 26,  3, 19,  5, 13,  8,  3,  4, 12],
       [26, 27,  4, 10,  6, 19,  5,  7, 19, 20],
       [13,  4,  7, 12, 20, 27, 30, 19, 16, 19],
       [10, 28, 17, 31, 17,  4, 18, 33,  4, 28],
       [15, 29,  2, 18, 15, 29, 22, 33, 23,  3],
       [ 6,  9,  2, 21, 20,  3, 27, 23, 30,  6],
       [15, 17,  4, 12, 14, 29,  9, 32, 17, 31],
       [22, 30,  9,  4, 15,  5, 21, 27, 29, 16],
       [20, 33,  2, 25, 29, 27, 13, 10, 16, 22]], dtype=int32)

In [69]:
np.random.randint(2,34,(10,10))

array([[29,  9,  9,  4, 17,  8, 32, 13,  5, 13],
       [ 9, 25, 20, 19,  3, 20, 32, 20, 13, 11],
       [16, 14, 11, 31, 10,  5, 20, 21, 11, 11],
       [25, 26, 21, 10, 32,  7, 32,  4,  3, 25],
       [25, 10, 23, 28, 31, 33,  6, 30, 27, 13],
       [21,  6, 11,  4,  3, 31, 13,  2, 18, 28],
       [ 7, 20, 25, 24, 28, 24, 21,  4, 22, 17],
       [ 9, 11,  9, 13, 30, 23, 16, 19,  6,  8],
       [15, 19,  2, 10,  3, 10, 19, 14,  3, 29],
       [33, 25,  6, 18, 19, 17, 16, 22, 10, 16]], dtype=int32)

In [70]:
arr

array([0, 1, 2, 3, 4, 5])

In [72]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [73]:
arr.reshape(8,3)

ValueError: cannot reshape array of size 6 into shape (8,3)

# Slicing in matrix

In [74]:
b = np.random.randint(10,20,(5,4))
b

array([[17, 12, 16, 10],
       [13, 19, 11, 11],
       [16, 11, 11, 13],
       [12, 12, 10, 19],
       [13, 19, 11, 12]], dtype=int32)

In [75]:
b[:]

array([[17, 12, 16, 10],
       [13, 19, 11, 11],
       [16, 11, 11, 13],
       [12, 12, 10, 19],
       [13, 19, 11, 12]], dtype=int32)

In [76]:
b[1:4]

array([[13, 19, 11, 11],
       [16, 11, 11, 13],
       [12, 12, 10, 19]], dtype=int32)

In [77]:
b[-1:]

array([[13, 19, 11, 12]], dtype=int32)

In [78]:
b[:-1]

array([[17, 12, 16, 10],
       [13, 19, 11, 11],
       [16, 11, 11, 13],
       [12, 12, 10, 19]], dtype=int32)

In [79]:
b[1,2]

np.int32(11)

# Numpy operations 

In [80]:
arr

array([0, 1, 2, 3, 4, 5])

In [81]:
arr.max()

np.int64(5)

In [84]:
from numpy import  *
mean(arr)

np.float64(2.5)

# indexing in numpy

In [96]:

np.random.randint(2,34,(10,10))

array([[23, 20, 18, 26,  4, 16, 25, 25,  7,  5],
       [28, 18, 32, 10, 22, 19, 22, 11, 18,  9],
       [ 8, 32, 18, 20, 27, 29, 32,  5,  7, 20],
       [30, 28,  2, 27, 12, 18, 23,  7, 33, 13],
       [31, 32, 18, 30, 12, 21, 20,  7, 10, 11],
       [26, 15, 13, 30, 29, 25, 24, 12,  7, 17],
       [16, 19,  5, 25,  5,  8, 19, 29, 11, 16],
       [23, 10, 12, 18, 27, 19, 32, 31, 25,  6],
       [15, 33, 15, 18, 32,  4, 10, 17, 16, 13],
       [15, 20,  4, 33, 11, 32, 18, 12, 29,  7]], dtype=int32)

In [97]:
np.random.randint(10,18,(2,6))

array([[13, 13, 16, 12, 11, 13],
       [15, 13, 16, 11, 13, 16]], dtype=int32)

In [104]:
m = np.arange(0,100).reshape(10,10)
print(m)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [110]:
row =5
col=3


In [111]:
row

5

In [112]:
col

3

In [113]:
m[row, col]

np.int64(53)

In [114]:
m[:,col]

array([ 3, 13, 23, 33, 43, 53, 63, 73, 83, 93])

In [115]:
m[3:]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [116]:
m[3]

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [117]:
m[:,7]

array([ 7, 17, 27, 37, 47, 57, 67, 77, 87, 97])

In [118]:
m[4:7]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [120]:
m[-4]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [121]:
print(m)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [122]:
m[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [123]:
m[::-2]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [124]:
m[2:6, 3:4]

array([[23],
       [33],
       [43],
       [53]])

# Masking

In [125]:
m

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [127]:
m[m<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [129]:
m[m!=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])